version: "3"

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    cmds:
      - task --list-all

  install:
    cmds:
      - uv sync

  db-fill:
    cmds:
      - uv run load_wiki_data.py

  chat:
    cmds:
      - uv run main.py

  ui:
    cmds:
      - uv run streamlit run app.py
