version: "3"

env:
  DB_NAME: my_table_two
  OLLAMA_HOST: 0.0.0.0
  OPENAI_BASE_URL: http://localhost:5000/v1

tasks:
  default:
    cmds:
      - task --list-all

  install:
    cmds:
      - uv sync

  fill-db:
    cmds:
      - uv run load_wiki_data.py

  chat:
    cmds:
      - uv run main.py

  ui:
    cmds:
      - streamlit run app.py
