version: "3"

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

includes:
  ui: ./ui
  mw: ./middleware

tasks:
  default:
    cmds:
      - task --list-all

  install:
    cmds:
      - uv sync

  db-fill:
    cmds:
      - uv run load_wiki_data.py

  chat:
    cmds:
      - uv run main.py
  
  dev:
    cmds:
      - task ui:ui &
      - task mw:dev

  #ui:
    #cmds:
      #- uv run streamlit run app.py
