version: "3"

env:
  DB_NAME: my_table_two
  OPENAI_BASE_URL: http://localhost:5000/v1
  MODEL: Qwen_Qwen2.5-1.5B-Instruct

tasks:
  default:
    cmds:
      - task --list-all

  install:
    cmds:
      - uv sync

  db-fill:
    cmds:
      - uv run load_wiki_data.py

  chat:
    cmds:
      - uv run main.py

  ui:
    cmds:
      - streamlit run app.py
